2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_setup.py:_flush():71] setting env: {}
2021-11-15 14:28:16,656 WARNING MainThread:8984 [wandb_setup.py:_flush():71] could not find program at C:\Users\Spectra\AppData\Local\Programs\Python\Python37\Scripts\pytest.exe\__main__.py
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_init.py:_log_setup():357] Logging user logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211115_142816-3iwfr9tz\logs\debug.log
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_init.py:_log_setup():358] Logging internal logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211115_142816-3iwfr9tz\logs\debug-internal.log
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_init.py:init():390] calling init triggers
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-15 14:28:16,656 INFO    MainThread:8984 [wandb_init.py:init():435] starting backend
2021-11-15 14:28:16,656 INFO    MainThread:8984 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-15 14:28:16,672 INFO    MainThread:8984 [backend.py:ensure_launched():199] starting backend process...
2021-11-15 14:28:16,765 INFO    MainThread:8984 [backend.py:ensure_launched():205] started backend process with pid: 4428
2021-11-15 14:28:16,765 INFO    MainThread:8984 [wandb_init.py:init():444] backend started and connected
2021-11-15 14:28:16,765 INFO    MainThread:8984 [wandb_init.py:init():503] updated telemetry
2021-11-15 14:28:16,859 INFO    MainThread:8984 [wandb_init.py:init():533] communicating current version
2021-11-15 14:28:18,667 INFO    MainThread:8984 [wandb_init.py:init():538] got version response 
2021-11-15 14:28:18,667 INFO    MainThread:8984 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-15 14:28:19,046 INFO    MainThread:8984 [wandb_init.py:init():576] starting run threads in backend
2021-11-15 14:28:22,369 INFO    MainThread:8984 [wandb_run.py:_console_start():1693] atexit reg
2021-11-15 14:28:22,384 INFO    MainThread:8984 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-11-15 14:28:22,384 INFO    MainThread:8984 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-11-15 14:28:22,384 INFO    MainThread:8984 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-15 14:28:22,384 INFO    MainThread:8984 [wandb_init.py:init():603] run started, returning control to user process
2021-11-15 14:28:24,242 INFO    MainThread:8984 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-11-15 14:28:24,243 INFO    MainThread:8984 [wandb_run.py:_restore():1635] restore
2021-11-15 14:28:24,428 INFO    MainThread:8984 [wandb_run.py:_restore():1635] restore
2021-11-15 14:28:27,246 ERROR   MainThread:8984 [wandb_run.py:_atexit_cleanup():1681] Problem finishing run
Traceback (most recent call last):
  File "c:\users\spectra\appdata\local\programs\python\python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1671, in _atexit_cleanup
    self._on_finish()
  File "c:\users\spectra\appdata\local\programs\python\python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1839, in _on_finish
    print("")
ValueError: I/O operation on closed file.
