2021-11-10 18:49:26,395 INFO    MainThread:13228 [wandb_setup.py:_flush():71] setting env: {}
2021-11-10 18:49:26,395 INFO    MainThread:13228 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-10 18:49:26,397 INFO    MainThread:13228 [wandb_init.py:_log_setup():357] Logging user logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211110_184926-17ayot7i\logs\debug.log
2021-11-10 18:49:26,398 INFO    MainThread:13228 [wandb_init.py:_log_setup():358] Logging internal logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211110_184926-17ayot7i\logs\debug-internal.log
2021-11-10 18:49:26,398 INFO    MainThread:13228 [wandb_init.py:init():390] calling init triggers
2021-11-10 18:49:26,412 INFO    MainThread:13228 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-10 18:49:26,413 INFO    MainThread:13228 [wandb_init.py:init():435] starting backend
2021-11-10 18:49:26,413 INFO    MainThread:13228 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-10 18:49:26,450 INFO    MainThread:13228 [backend.py:ensure_launched():199] starting backend process...
2021-11-10 18:49:26,756 INFO    MainThread:13228 [backend.py:ensure_launched():205] started backend process with pid: 4976
2021-11-10 18:49:26,758 INFO    MainThread:13228 [wandb_init.py:init():444] backend started and connected
2021-11-10 18:49:26,759 INFO    MainThread:13228 [wandb_init.py:init():503] updated telemetry
2021-11-10 18:49:26,980 INFO    MainThread:13228 [wandb_init.py:init():533] communicating current version
2021-11-10 18:49:30,068 INFO    MainThread:13228 [wandb_init.py:init():538] got version response 
2021-11-10 18:49:30,069 INFO    MainThread:13228 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-10 18:50:00,084 INFO    MainThread:13228 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-11-10 18:50:00,084 ERROR   MainThread:13228 [wandb_init.py:init():553] backend process timed out
2021-11-10 18:50:00,084 ERROR   MainThread:13228 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-11-10 18:51:01,352 INFO    MainThread:13228 [wandb_init.py:teardown():205] tearing down wandb.init
